import { Apartment } from "../types"

export const apartments: Apartment[] = [
  {
    id: "1",
    title: "Flat in Battersea Rise",
    address: {
      doorNumber: "12",
      street: "Falcon Road",
      city: "London",
      postcode: "SW11 2LG",
      country: "UK",
    },
    pricePerMonth: 1700,
    images: [
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707082992/u9ucrlazngssj7sukui6.webp",
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707147726/ybkgtobaquxdadf0vszz.png",
    ],
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    propertyType: "Entire Flat",
    bookingDate: "December 2nd, 2023 at 09:30",
    amenities: ["WiFi", "Air Conditioning", "Gym"],
    description: "A spacious two-bedroom flat with modern amenities and a great view of the park.",
    squareFeet: 850,
    viewingDate: "December 4th, 2023 at 19:45",
    available: false,
  },
  {
    id: "2",
    title: "Camden Charm",
    address: {
      doorNumber: "24B",
      street: "Camden High Street",
      city: "London",
      postcode: "NW1 8QP",
      country: "UK",
    },
    pricePerMonth: 1700,
    images: [
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707082992/kquayhvbqgibsttlsy5c.webp",
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707082992/u9ucrlazngssj7sukui6.webp",
    ],
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    propertyType: "Studio",
    bookingDate: "December 2nd, 2023 at 09:30",
    bookingCancellationDate: "December 3rd, 2023 at 15:27",
    amenities: ["WiFi", "Air Conditioning", "Gym"],
    description: "A spacious two-bedroom flat with modern amenities and a great view of the park.",
    squareFeet: 850,
    viewingDate: "December 4th, 2023 at 19:45",
    available: true,
  },
  {
    id: "3",
    title: "Shoreditch Suite",
    address: {
      doorNumber: "37A",
      street: "Shoreditch High Street",
      city: "London",
      postcode: "E1 6PQ",
      country: "UK",
    },
    pricePerMonth: 1700,
    images: [
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707147717/oiye6wflkfknhovotwpe.png",
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707082992/kquayhvbqgibsttlsy5c.webp",
    ],
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    propertyType: "Entire Flat",
    bookingDate: "December 2nd, 2023 at 09:30",
    amenities: ["WiFi", "Air Conditioning", "Gym"],
    description: "A spacious two-bedroom flat with modern amenities and a great view of the park.",
    squareFeet: 850,
    viewingDate: "December 4th, 2023 at 19:45",
    available: false,
  },
  {
    id: "4",
    title: "Greenwich Gallery",
    address: {
      doorNumber: "56",
      street: "Trafalgar Road",
      city: "London",
      postcode: "SE10 9UW",
      country: "UK",
    },
    pricePerMonth: 1700,
    images: [
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707147726/ybkgtobaquxdadf0vszz.png",
      "https://res.cloudinary.com/thunder-fusion/image/upload/w_400,f_auto,q_auto/v1707147717/oiye6wflkfknhovotwpe.png",
    ],
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    propertyType: "Room",
    bookingDate: "December 2nd, 2023 at 09:30",
    amenities: ["WiFi", "Air Conditioning", "Gym"],
    description: "A spacious two-bedroom flat with modern amenities and a great view of the park.",
    squareFeet: 850,
    viewingDate: "December 4th, 2023 at 19:45",
    available: true,
  },
]
